name: launcher
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#  System level
  device_apps: ^2.2.0
  app_settings: ^5.1.1

# "state manager"
  flutter_riverpod: ^2.3.0
  receive_intent: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
