name: launcher
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+11

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#  System level
  device_apps: ^2.2.0
  app_settings: ^5.1.1

# "state manager"
  flutter_riverpod: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/png/launcher.png"
  min_sdk_android: 26

flutter:
  uses-material-design: true


